McvExamenCubos/Controllers/ManagedController.cs
using McvExamenCubos.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace McvExamenCubos.Controllers
{
    public class ManagedController : Controller
    {

        private ServiceCubos service;
        private ServiceStorageBlobs serviceblobs;

        public ManagedController(ServiceCubos service, ServiceStorageBlobs serviceblobs)
        {
            this.service = service;
            this.serviceblobs = serviceblobs;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            string token = await this.service.GetTokenAsync(username, password);

            if (token == null)
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
            }
            else
            {
                HttpContext.Session.SetString("TOKEN", token);
                ClaimsIdentity identity =
                    new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, 
                    ClaimTypes.Name, ClaimTypes.Role);

                identity.AddClaim(new Claim(ClaimTypes.Name, username));
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, password));
                ClaimsPrincipal userPrincipal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        userPrincipal, new AuthenticationProperties
                        {
                            ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(30)
                        });
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Remove("TOKEN");
            return RedirectToAction("Index", "Home");
        }


        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(string nombre, string email, string password, IFormFile file)
        {
            string blobName = file.FileName;
            using (Stream stream = file.OpenReadStream())
            {
                await this.serviceblobs.UploadBlobAsync
                ("imagenesperfil", blobName, stream);

            }

            await this.service.GetRegisterUserAsync(nombre, email, password, blobName);

            return RedirectToAction("Login");
        }
    }
}

McvExamenCubos/ViewComponents/MenuMarcasViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using McvExamenCubos.Models;
using McvExamenCubos.Services;

namespace McvExamenCubos.ViewComponents
{
    public class MenuMarcasViewComponent : ViewComponent
    {

        private ServiceCubos service;

        public MenuMarcasViewComponent(ServiceCubos service)
        {
            this.service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<string> marcas = await this.service.GetMarcas();
            return View(marcas);

        }
    }
}

McvExamenCubos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - McvExamenCubos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/McvExamenCubos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">McvExamenCubos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="Index">Tienda</a>
                        </li>
                        <li>@await Component.InvokeAsync("MenuMarcas")</li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tienda" asp-action="InsertarProducto">Insertar Producto</a>
                        </li>
                        <partial name="_MenuUsuario" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - McvExamenCubos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

McvExamenCubos/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated)
{

    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Perfil">Mi Perfil</a>
    <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Pedidos">Mi Pedidos</a>


    <a class="nav-link" asp-controller="Managed" asp-action="Logout">
        Log Out
        <span style="color:blue">@Context.User.Identity.Name</span>
    </a>
}
else
{
    <a class="nav-link text-danger" asp-controller="Managed" asp-action="Register">
        Register
    </a>
    <a class="nav-link text-danger" asp-controller="Usuarios" asp-action="Index">
        Log In
    </a>
}